// web-admin/src/pages/Settings.svelte
<script lang="ts">
  import { darkMode, apiUrl } from "../stores";
</script>

<div class="container container-small">
  <div class="row">
    <div class="col align-center">
      <h2>Settings</h2>
      <section>
        <p>
          <button on:click={() => darkMode.update((m) => !m)}>
            Your colorscheme is
            {$darkMode ? "Dark Mode" : "Light Mode"}
          </button>
        </p>
        <div class="form-control">
          <label>
            Your CDL's GraphQL API URL
            <input
              type="url"
              value={$apiUrl}
              on:input={(event) => apiUrl.set(event.currentTarget.value)}
            />
          </label>
        </div>
      </section>
    </div>
  </div>
</div>

// cdl-site/src/pages/settings.tsx
import { FunctionalComponent, h } from "preact";
import { useContext } from "preact/hooks";

import CdlContext from "../context";

const Settings: FunctionalComponent = () => {
    const { darkMode, toggleDarkMode } = useContext(CdlContext);

    return (
        <div class="container container-small">
            <div class="row">
                <div class="col align-center">
                    <h2>Settings</h2>
                    <br />
                    <p>
                        <button onClick={toggleDarkMode}>
                            Your colorscheme is {darkMode ? "Dark Mode" : "Light Mode"}
                        </button>
                    </p>
                </div>
            </div>
        </div>
    );
};

export default Settings;
